#include <errno.h>
#include <stdio.h>

typedef enum fopen_err
{
    FOPEN_NO_ACCESS = EACCES,
    FOPEN_BAD_FILE_DESCRIPTOR = EBADF,
    FOPEN_EXISTS = EEXIST,
    FOPEN_TOO_BIG = EFBIG,
    FOPEN_INVALID_ARGUMENT = EINVAL,
    FOPEN_TOO_MANY_FILES_DESCRIPTORS = EMFILE,
    FOPEN_NAME_TOO_LONG = ENAMETOOLONG,
    FOPEN_TOO_MANY_FILES_OPEN = ENFILE,
    FOPEN_DOES_NOT_EXIST = ENOENT,
    FOPEN_READ_ONLY = EROFS,
    FOPEN_CROSS_DEVICE_LINK = EXDEV,
    FOPEN_TEXT_FILE_BUSY = ETXTBSY,
} fopen_err;

typedef enum fclose_err
{
    FCLOSE_INVALID_ARGUMENT = EINVAL,
} fclose_err;
